---
# tasks file for minio_role

- name: Download MinIO binary
  get_url:
    url: "{{ minio_download_url }}"
    dest: "{{ minio_deb_path }}"
    mode: "{{ deb_file_mode }}"
  become: yes

- name: Install MinIO binary
  apt:
    deb: "{{ minio_deb_path }}"
  become: yes
