

  - name: Download MinIO binary
    get_url:
      url: https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20240731054626.0.0_amd64.deb
      dest: /tmp/minio.deb
      mode: '0755'
    become: yes

  - name: Install MinIO binary
    apt:
      deb: /tmp/minio.deb
    become: yes


  

 


   
