---

- name: Install required packages on RedHat-based systems
  yum:
    name:
      - wget
      - unzip
    state: present
  when: ansible_os_family == "RedHat"

- name: Install required packages on Debian-based systems
  apt:
    name:
      - wget
      - unzip
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: yes

- name: Install required packages on CentOS
  yum:
    name:
      - wget
      - unzip
    state: present
  when: ansible_distribution == "CentOS"
  become: yes

- name: Download MinIO binary
  get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
    dest: "/usr/local/bin/minio"
    mode: '0755'

- name: Create MinIO service file on RedHat-based systems
  template:
    src: "minio.service.j2"
    dest: "/etc/systemd/system/minio.service"
  when: ansible_os_family == "RedHat"

- name: Create MinIO service file on Debian-based systems
  template:
    src: "minio.service.j2"
    dest: "/etc/systemd/system/minio.service"
  when: ansible_os_family == "Debian"

- name: Create MinIO service file on CentOS
  template:
    src: "minio.service.j2"
    dest: "/etc/systemd/system/minio.service"
  when: ansible_distribution == "CentOS"

- name: Update apt package list
  ansible.builtin.apt:
    update_cache: "{{ update_cache }}"
  become: yes
  
- name: Download MinIO binary
  get_url:
    url: "{{ minio_download_url }}"
    dest: "{{ minio_deb_path }}"
    mode: "{{ deb_file_mode }}"
  become: yes

- name: Install MinIO binary
  apt:
    deb: "{{ minio_deb_path }}"
  become: yes

- name: Ensure MinIO binary has execute permissions
  file:
    path: "{{ minio_deb_path }}" 
    mode: '0755'
    owner: minio
    group: minio
  become: yes








