---
# tasks file for minio_role
- name: Install MinIO
  include_tasks: install.yml

- name: Configure MinIO
  include_tasks: configure.yml

- name: Manage MinIO service
  include_tasks: service.yml


- name: Update APT package index (Debian)
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: yes

- name: Ensure essential packages are installed (Debian)
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - git
    - curl
    - wget
  when: ansible_os_family == "Debian"
  become: yes

- name: Ensure essential packages are installed (RedHat/CentOS)
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - git
    - curl
    - wget
  when: ansible_os_family == "RedHat"
  become: yes



