---
# Tasks for Debian-based systems

- name: Update apt package list
  ansible.builtin.apt:
    update_cache: "{{ update_cache }}"
  become: yes

- name: Install MinIO
  include_tasks: "install.yml"

- name: Configure MinIO
  include_tasks: "{{ configure_tasks_file }}"


- name: Include task variables
  include_vars: vars/main.yml

- name: Ensure MinIO data directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: minio
    group: minio
    mode: '0755'
  loop: "{{ minio_data_dirs[deployment_type] }}"
  when: deployment_type in ['single-node-single-drive', 'single-node-multi-drive', 'multi-node-multi-drive']

- name: Start MinIO server with the chosen deployment type
  include_tasks: "{{ deployment_type }}.yml"
  when: deployment_type in ['single-node-single-drive', 'single-node-multi-drive', 'multi-node-multi-drive']
