---
# Tasks for Debian-based systems

- name: Update apt package list
  ansible.builtin.apt:
    update_cache: "{{ update_cache }}"
  become: yes

- name: Install MinIO
  include_tasks: "{{ install_tasks_file }}"

- name: Configure MinIO
  include_tasks: "{{ configure_tasks_file }}"


- name: Include task variables
  include_vars: vars/main.yml
    

- name: Setup MinIO
  include_tasks: "setup_{{ minio_deployment_type }}.yml"
     


