---
- name: Validate system & prerequisites
  ansible.builtin.include_tasks: prerequisites.yml

- name: Install MinIO
  ansible.builtin.include_tasks: install.yml

- name: Configure MinIO
  ansible.builtin.include_tasks: configure.yml

- name: Configure security (TLS / permissions)
  ansible.builtin.include_tasks: security.yml

- name: Configure observability
  ansible.builtin.include_tasks: observability.yml
  when: minio_observability_enabled | bool

- name: Configure and start MinIO service
  ansible.builtin.include_tasks: service.yml

- name: Configure MinIO access (users & policies)
  ansible.builtin.include_tasks: access.yml
  when:
    - minio_manage_access | bool
    - minio_users is defined
    - minio_users | length > 0

- name: Verify MinIO availability
  ansible.builtin.include_tasks: verify.yml
